### ISSUE TITLE
New word suggestions

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/tYp3r#3]
Following suggestions I had in mind:
`there` : `der`
`love` : `lub`
`brother` : `bro` or `bruh`
Also, the probability of `life` changing to `lyf` seems very low.

**Comment by aviaryan** [comment]
> brother : bro or bruh

This isn't suitable because it changes the syllables i.e. the sound of the word which may not be liked by some users. 

> Also, the probability of life changing to lyf seems very low.

I don't understand. We don't have such a substitution, do we?

**Comment by Monal5031** [comment]
@aviaryan We can make `brother` to then `broda`

**Comment by aviaryan** [comment]
@Monal5031 Yes, sure. Also `love->luv` works... Not sure about `there->der`.

**Comment by Monal5031** [comment]
@aviaryan `there`  replacing with `der` seems to be same as `this` by `dis`
